# image:
#   file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: | # runs during prebuild
    sudo curl -L https://get.ignite.com/cli@v${IGNITE_VERSION} | bash -
    sudo mv ignite /usr/local/bin

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
